### ISSUE TITLE
Slideshow on fronts

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/dotcom-rendering#5655] opened 2022-08-10 13:29 UTC
We need to implement the slideshow on fronts in DCR

https://user-images.githubusercontent.com/31692/183913793-bb848c51-f6c6-4038-9e33-11b3e5790928.mp4

**Comment by oliverlloyd** [comment] 2022-08-18 16:23
Duplicate of https://github.com/guardian/dotcom-rendering/issues/4612

**Closed by oliverlloyd** 2022-08-18 16:23 UTC

**Comment by jamesgorrie** [comment] 2022-10-05 14:16
@oliverlloyd is this a duplicate to a carousel? I didn't realise they were the same thing.
