### ISSUE TITLE
Pictures: Image Slideshow

### ISSUE THREAD

**Issue by VDuczekW** [guardian/dotcom-rendering#6380] opened 2022-11-04 15:55 UTC
Investigation needed
Is this a dupe? [#4612](https://github.com/guardian/dotcom-rendering/issues/4612)

**Comment by rhiannareechaye** [comment] 2023-03-23 12:27
This is a dupe of [Slideshow on fronts#5654](https://github.com/guardian/dotcom-rendering/issues/5654)

**Closed by rhiannareechaye** 2023-03-23 12:27 UTC
