### ISSUE TITLE
Slideshow on fronts

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/dotcom-rendering#5654] opened 2022-08-10 13:10 UTC
Some Cards have an image carousel. Those images should have captions

**Comment by AshCorr** [comment] 2022-10-06 10:14
Currently on frontend we allow a card to contain a slideshow of up to 5 images that will switch images sequentially every 5 seconds. This gets used fairly often in big stories on network Headline containers so its fairly important to get this working before we migrate.

Currently slideshows are not super accessible and don't have the greatest UX experience as theres no way for the user to control a slideshow (eg, pausing, going back an image, etc). Do we want to re-consider the current pure CSS approach to slideshows for something like JS to allow us to build in more controls to slideshows?

**Comment by rhiannareechaye** [comment] 2023-03-23 12:07
@AshCorr Am assuming we need this ticket for Fronts 100% and we're saying we may implement in a slightly different way?

**Comment by paperboyo** [comment] 2023-05-05 11:19
Duplicate of https://github.com/guardian/dotcom-rendering/issues/4612.

UX/accessibilty aside, frontend’s slideshows have some proper bugs/inefficiencies:
- picture element fallback URL points to a `master` asset (!)
- all images are loaded by the browser for all slideshows on all cards **even if the card is so small that the slideshow isn’t visible**

**Comment by AshCorr** [comment] 2023-05-11 11:31
> @AshCorr Am assuming we need this ticket for Fronts 100% and we're saying we may implement in a slightly different way?

We might want to look at doing it in a more accessible way!

**Comment by rhiannareechaye** [comment] 2023-06-05 10:52
https://github.com/guardian/dotcom-rendering/pull/7852

**Closed** 2023-06-08 12:34 UTC
Labels: Fronts :newspaper:
