### ISSUE TITLE
dynamic/package Live blog blocks should show under headline

### ISSUE THREAD

**Issue by DanielCliftonGuardian** [guardian/dotcom-rendering#6493] opened 2022-11-17 13:37 UTC
Frontend: 
<img width="971" alt="image" src="https://user-images.githubusercontent.com/110032454/202460626-79e0973c-6e84-4669-a538-9ad372f75ffb.png">
DCR: 
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/110032454/202460699-c18d346f-7935-4bd6-ad8c-86bbf6bdb6e8.png">

**Comment by rhiannareechaye** [comment] 2023-03-28 14:17
Duplicate of https://github.com/orgs/guardian/projects/90/views/1?pane=issue&itemId=24145583

**Closed by rhiannareechaye** 2023-03-28 14:17 UTC
Labels: Fronts :newspaper:
