### ISSUE TITLE
[Epic]: DCR for Apps - Sports blogs

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/dotcom-rendering#8746] opened 2023-09-05 08:04 UTC
The way we show features that are specific to sports blogs e.g.
- Match stats
- Scoreboards
- ???

is different across Apps and Web. 

It has generally been considered by UX and design (CC @ajbreuer) that the app is a better experience.

We should bare this in mind when moving content over, and is probably a good, larger discussion for one of our design reviews.

**Comment by JamieB-gu** [comment] 2024-10-21 12:32
Duplicate of #7396

**Closed by JamieB-gu** 2024-10-21 12:32 UTC
