### ISSUE TITLE
Caption at tablet breakpoint needs some margin-left

### ISSUE THREAD

**Issue by VDuczekW** [guardian/dotcom-rendering#4483] opened 2022-03-31 13:48 UTC
<img width="510" alt="image" src="https://user-images.githubusercontent.com/91130034/161070826-c45f9968-e556-4acb-955f-2b0cfdd4684e.png">

**Comment by AshCorr** [comment] 2022-04-19 09:51
Duplicate of #4150

**Closed by AshCorr** 2022-04-19 09:51 UTC
Labels: bug, Liveblogs
