### ISSUE TITLE
Multiple open tabs crash Firefox on Android

### ISSUE THREAD

**Issue by mxdvl** [guardian/dotcom-rendering#6103] opened 2022-10-03 12:52 UTC
When opening multiple background tabs from a fronts in Firefox for Android, the tabs will hang and crash. Eventually, crashed tab will reload and the pages are then viewable.

Reported by @undergroundquizscene.

**Comment by undergroundquizscene** [comment] 2022-10-03 17:06
Thanks for opening the issue, @mxdvl! I’d better confirm the problem is still happening, and provide precise reproduction steps – shouldn’t take long.

**Comment by undergroundquizscene** [comment] 2022-10-03 17:18
Yes, I have confirmed that the bug is still happening. Here’s what I did, and what happened:

I loaded the guardian homepage in Firefox for Android version 105.1.0. (I am using a OnePlus 6, in case that’s relevant.) I long-pressed on one article link, selected “open in new tab”, then waited a moment and repeated. 

After opening the second article in a new tab, the first tab lost interactivity – long-pressing on links didn’t bring up the context menu. Scrolling down on that tab showed that the rendering had stopped shortly below the initial viewport.

![Screenshot_20221003-180904](https://user-images.githubusercontent.com/23191049/193638455-ec691757-7359-4a15-b363-6113bf41f302.jpg)

Switching to the new tabs (for the first time) showed that they were completely white, not rendering at all.

![Screenshot_20221003-180912](https://user-images.githubusercontent.com/23191049/193638660-71b06175-8ca0-4dac-ad34-7a36102dafd3.jpg)

My memory is that waiting on these tabs eventually crashed firefox, though I did not confirm that this time.

**Comment by rhiannareechaye** [comment] 2023-04-27 09:08
We are deprioritising this ticket by 'closing a not planned' - this won't delete the ticket and it will be searchable if the issue crops up again. Unfortunately we have over 130 health tickets to address in the web team. With so many tickets we are potentially missing things that are high-impact so we're reorganising the board - if we can get through all our high-impact tickets we can re-open these lower impact ones.

**Comment by rhiannareechaye** [comment] 2023-04-27 09:09
We are deprioritising this ticket by 'closing a not planned' - this won't delete the ticket and it will be searchable if the issue crops up again. Unfortunately we have over 130 health tickets to address in the web team. With so many tickets we are potentially missing things that are high-impact so we're reorganising the board - if we can get through all our high-impact tickets we can re-open these lower impact ones.

**Closed by rhiannareechaye** 2023-04-27 09:09 UTC
Labels: bug, Could, dotcom-rendering

**Comment by undergroundquizscene** [comment] 2023-04-28 09:34
@rhiannareechaye That’s understandable, thanks for letting me know!

**Comment by emdash-ie** [comment] 2024-05-19 15:33
I have learned more about the cause of this issue, and opened https://github.com/guardian/commercial/issues/1388 as a better home for it.
