### ISSUE TITLE
Update Standfirst size and weight for Standard Articles 

### ISSUE THREAD

**Issue by alinaboghiu** [guardian/dotcom-rendering#9082] opened 2023-10-10 09:24 UTC
On a Standard Display/Article Design, things that need updating are:
- font weight: always 500
- font size: mobile 17px, desktop 24px 
- maybe line height
- width 

Check designs here for the last two things: https://www.figma.com/file/xPr2tZZger7pszcO075tAQ/New-Formats---April-23?type=design&node-id=2002-24784&mode=design&t=Lj8ecf02dRAyfYuY-0

**Comment by JamieB-gu** [comment] 2023-10-18 17:33
Duplicate of #9185

**Closed by JamieB-gu** 2023-10-18 17:33 UTC
