### ISSUE TITLE
`Role: Immersive` Elements Overlap Right Column Content

### ISSUE THREAD

**Issue by cemms1** [guardian/dotcom-rendering#9545] opened 2023-11-17 10:45 UTC
When elements have `role: immersive` they span both the centre and the right column from `desktop` (and all three columns from `leftCol`). This means they overlap content that appears in the right column, including adverts and "most viewed".

## Example

This can be seen on [this article](https://www.theguardian.com/world/2023/nov/16/when-delhis-air-pollution-gets-worse-a-photographic-comparison), which contains a number of interactive elements with `role: immersive` and was reported in [this email from CP](https://groups.google.com/a/guardian.co.uk/g/dotcom.platform/c/LSgovjt7iC8).

![role-immersive-ad](https://github.com/guardian/dotcom-rendering/assets/53781962/a249deb4-f285-427e-8ab9-b8c2870915c8)

***

![role-immersive-most-viewed](https://github.com/guardian/dotcom-rendering/assets/53781962/444776be-5871-42aa-8e9e-1a47c94a6a8f)

## Solutions

This isn't a content problem. It's valid to have a piece of content to have one or more elements with `role: immersive` set anywhere in the body. The fact that the platform design on wider breakpoints (desktop upwards) doesn't allow for this is a problem for the platforms to solve.

1. We can't just push the right column content down because, as seen in the example article above, there may not be space further down the right column either.

2. We could choose to hide right column content when body elements have immersive roles. Commercial have a stake in this decision too, as it would mean hiding right column ads.

3. We could also choose not to have immersive content span into the right column, as appears to be the case for frontend: https://www.theguardian.com/world/2023/nov/16/when-delhis-air-pollution-gets-worse-a-photographic-comparison?dcr=false

**Comment by alinaboghiu** [comment] 2024-01-12 12:36
Duplicate of https://github.com/guardian/dotcom-rendering/issues/5108 I believe

**Closed by alinaboghiu** 2024-01-12 12:36 UTC
Labels: Bug, Rota
