### ISSUE TITLE
Image resolution

### ISSUE THREAD

**Issue by alinaboghiu** [guardian/dotcom-rendering#7941] opened 2023-06-16 10:39 UTC
Dynamic package full-with image [is loaded at 700px](https://m.code.dev-theguardian.com/sublinks-test?dcr#dynamic/package-(dynamo)) wide instead of 940px in Frontend leading to a low resolution

**Comment by rhiannareechaye** [comment] 2023-06-16 12:04
Duplicate of [Refactor image position#4822](https://github.com/guardian/dotcom-rendering/issues/4822)

**Closed by rhiannareechaye** 2023-06-16 12:04 UTC
Labels: bug, Must, Fronts Go-live
