### ISSUE TITLE
Poor image quality on immersive images

### ISSUE THREAD

**Issue by oliverlloyd** [guardian/dotcom-rendering#5878] opened 2022-08-30 07:05 UTC
If a main media image is given the role of `showcase` (you can choose between default and showcase) and then the article is given the display hint of immersive then this results in the image being shown as immersive but given the sources based on the showcase role. This means the quality is reduced

**Comment by mxdvl** [comment] 2022-08-30 09:17
Is this a duplicate of #5353 ?

**Closed** 2022-08-30 09:53 UTC
