### ISSUE TITLE
Make a plan to decide what to do with 'Message us' long term

### ISSUE THREAD

**Issue by rhiannareechaye** [guardian/dotcom-rendering#8152] opened 2023-07-05 10:24 UTC
We have a bit of a 'hacky version' - a time limited test of the features in the ed tools codebade (it's not in the capi model) 

Rhianna and Max + tools to decide where it should sit and whether or not it should be in production

**Comment by rhiannareechaye** [comment] 2023-07-27 13:29
Moving to EdEx health work

**Comment by alinaboghiu** [comment] 2024-03-21 09:33
We've decided to remove this feature. Keeping this ticket so we can track removal work.
cc @JamieB-gu

**Comment by JamieB-gu** [comment] 2024-08-07 17:02
Duplicate of #10571

**Closed by JamieB-gu** 2024-08-07 17:02 UTC
Labels: EdEx
